[tool.poetry]
name = "python-anywhere"
version = "0.1.0"
description = ""
authors = ["Desmond Bai <desmond.bai29@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
